import com.google.gson.Gson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.concurrent.ThreadLocalRandom;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static int main(String[] args) {
        Quote[] quotes = quoteArr();
        int random = ThreadLocalRandom.current().nextInt(quotes.length);
        System.out.println(quotes[random]);
        return random;
//        try {
//            byte[] text = Files.readAllBytes(Paths.get("assets/recentquotes.json"));
//            Gson gson = new Gson();
//            Quote[] quotes = gson.fromJson(new String(text), Quote[].class);
//            int random = ThreadLocalRandom.current().nextInt(quotes.length);
//            System.out.println(random);
//
//        }
//        catch (IOException e) {
//            System.err.println(e);
//        }
    }

    public static Quote[] quoteArr () {
        try {
            byte[] text = Files.readAllBytes(Paths.get("assets/recentquotes.json"));
            Gson gson = new Gson();
            Quote[] quotes = gson.fromJson(new String(text), Quote[].class);
            return quotes;

        }
        catch (IOException e) {
            System.err.println(e);
            return null;
        }
    }
}
