import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        try {
            byte[] text = Files.readAllBytes(Paths.get("assets/recentquotes.json"));
            System.out.println(new String(text));
        }
        catch (IOException e) {
            System.err.println(e);
        }
    }
}
