/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assert.*;

public class AppTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final ByteArrayOutputStream errContent = new ByteArrayOutputStream();
    private final PrintStream originalOut = System.out;
    private final PrintStream originalErr = System.err;

    @Before
    public void setUpStreams() {
        System.setOut(new PrintStream(outContent));
        System.setErr(new PrintStream(errContent));
    }

    @After
    public void restoreStreams() {
        System.setOut(originalOut);
        System.setErr(originalErr);
    }
    @Test public void testAppMain() {
        int random = App.main(new String[0]);
        Quote[] quotes = App.quoteArr();
        assertTrue("app should print a quote and author with \" - \" between them", outContent.toString().contains(" - "));
        assertEquals("Should Return quote at random index of quote array as \"Quote\" - Author format", quotes[random].toString() + "\n", outContent.toString());
    }
}
